# Generated by Django 6.0.4 on 2026-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='São Paulo', help_text='Ex: São Paulo', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='SP', help_text='Ex: SP', max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=123, help_text='Ex: 123 ou 123A', max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='Avenida Paulista', help_text='Ex: Avenida Paulista', max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Digite o nome completo do cliente', max_length=100, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
